//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotmim.Sample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotmim.Sample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @TableName NVARCHAR(128), @SchemaName NVARCHAR(128), @ColumnName NVARCHAR(128), @Sql NVARCHAR(MAX);
        ///                        DECLARE cur CURSOR FOR
        ///                        SELECT TableName, SchemaName, ColumnName
        ///                        FROM 
        ///                        (
        ///                            SELECT t.name AS TableName, s.name AS SchemaName, c.name AS ColumnName, 
        ///                                ROW_NUMBER() OVER(PARTITION BY t.object_id ORDER BY c.column_id) AS RowNum
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fakeupdate {
            get {
                return ResourceManager.GetString("fakeupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///
        ///CREATE DATABASE TestDb
        ///
        ///**GO**
        ///
        ///USE [TestDb]
        ///
        ///ALTER DATABASE TestDb SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 14 DAYS, AUTO_CLEANUP = ON)
        ///
        ///**GO**
        ///
        ///CREATE TABLE [dbo].[tbl_purchases](
        ///	[pk_purchase_id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[fk_vendor_id] [int] NULL,
        ///	[fk_payment_type_id] [int] NOT NULL,
        ///	[fk_item_id] [bigint] NOT NULL,
        ///	[purchase_datetime] [datetime] NOT NULL,
        ///	[fk_currency_id] [int] NOT NULL,
        ///	[purchase_amount] [decimal](8, 2) NOT NULL,
        ///	[description] [nvarc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string schema {
            get {
                return ResourceManager.GetString("schema", resourceCulture);
            }
        }
    }
}
